[package]
name = "wasm-c64"
version = "0.1.0"
authors = ["Andrew Imm <aimm22@gmail.com>"]

[lib]
name = "rustc64lib"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
c64memmap = {path = "lib/c64memmap"}
mos6510 = {path = "lib/mos6510"}