pub enum AddressMode {
  None,
  Immediate,
  Relative,
  ZeroPage,
  ZeroPageX,
  ZeroPageY,
  Absolute,
  AbsoluteX,
  AbsoluteY,
  Indirect,
  IndirectX,
  IndirectY,
}

type Instruction = (&'static str, AddressMode);

static INSTRUCTIONS: [Instruction; 0x60] = [
  ("BRK", AddressMode::None),
  ("ORA", AddressMode::IndirectX),
  ("KIL", AddressMode::None),
  ("SLO", AddressMode::IndirectX),
  ("DOP", AddressMode::ZeroPage),
  ("ORA", AddressMode::ZeroPage),
  ("ASL", AddressMode::ZeroPage),
  ("SLO", AddressMode::ZeroPage),
  ("PHP", AddressMode::None),
  ("ORA", AddressMode::Immediate),
  ("ASL", AddressMode::None),
  ("ANC", AddressMode::Immediate),
  ("TOP", AddressMode::Absolute),
  ("ORA", AddressMode::Absolute),
  ("ASL", AddressMode::Absolute),
  ("SLO", AddressMode::Absolute),

  ("BPL", AddressMode::Relative),
  ("ORA", AddressMode::IndirectY),
  ("KIL", AddressMode::None),
  ("SLO", AddressMode::IndirectY),
  ("DOP", AddressMode::IndirectX),
  ("ORA", AddressMode::IndirectX),
  ("ASL", AddressMode::IndirectX),
  ("SLO", AddressMode::IndirectX),
  ("CLC", AddressMode::None),
  ("ORA", AddressMode::AbsoluteY),
  ("NOP", AddressMode::None),
  ("SLO", AddressMode::AbsoluteY),
  ("TOP", AddressMode::AbsoluteX),
  ("ORA", AddressMode::AbsoluteX),
  ("ASL", AddressMode::AbsoluteX),
  ("SLO", AddressMode::AbsoluteX),

  ("JSR", AddressMode::Absolute),
  ("AND", AddressMode::IndirectX),
  ("KIL", AddressMode::None),
  ("RLA", AddressMode::IndirectX),
  ("BIT", AddressMode::ZeroPage),
  ("AND", AddressMode::ZeroPage),
  ("ROL", AddressMode::ZeroPage),
  ("RLA", AddressMode::ZeroPage),
  ("PLP", AddressMode::None),
  ("AND", AddressMode::Immediate),
  ("ROL", AddressMode::None),
  ("ANC", AddressMode::Immediate),
  ("BIT", AddressMode::Absolute),
  ("AND", AddressMode::Absolute),
  ("ROL", AddressMode::Absolute),
  ("RLA", AddressMode::Absolute),

  ("BMI", AddressMode::Relative),
  ("AND", AddressMode::IndirectY),
  ("KIL", AddressMode::None),
  ("RLA", AddressMode::IndirectX),
  ("DOP", AddressMode::ZeroPageX),
  ("AND", AddressMode::ZeroPageX),
  ("ROL", AddressMode::ZeroPageX),
  ("RLA", AddressMode::ZeroPageX),
  ("SEC", AddressMode::None),
  ("AND", AddressMode::AbsoluteY),
  ("NOP", AddressMode::None),
  ("RLA", AddressMode::AbsoluteY),
  ("TOP", AddressMode::AbsoluteX),
  ("AND", AddressMode::AbsoluteX),
  ("ROL", AddressMode::AbsoluteX),
  ("RLA", AddressMode::AbsoluteX),

  ("RTI", AddressMode::None),
  ("EOR", AddressMode::IndirectX),
  ("KIL", AddressMode::None),
  ("SRE", AddressMode::IndirectX),
  ("DOP", AddressMode::ZeroPage),
  ("EOR", AddressMode::ZeroPage),
  ("LSR", AddressMode::ZeroPage),
  ("SRE", AddressMode::ZeroPage),
  ("PHA", AddressMode::None),
  ("EOR", AddressMode::Immediate),
  ("LSR", AddressMode::None),
  ("ALR", AddressMode::Immediate),
  ("JMP", AddressMode::Absolute),
  ("EOR", AddressMode::Absolute),
  ("LSR", AddressMode::Absolute),
  ("SRE", AddressMode::Absolute),

  ("BVC", AddressMode::Relative),
  ("EOR", AddressMode::IndirectY),
  ("KIL", AddressMode::None),
  ("SRE", AddressMode::IndirectY),
  ("DOP", AddressMode::ZeroPageX),
  ("EOR", AddressMode::ZeroPageX),
  ("LSR", AddressMode::ZeroPageX),
  ("SRE", AddressMode::ZeroPageX),
  ("CLI", AddressMode::None),
  ("EOR", AddressMode::AbsoluteY),
  ("NOP", AddressMode::None),
  ("SRE", AddressMode::AbsoluteY),
  ("NOP", AddressMode::AbsoluteX),
  ("EOR", AddressMode::AbsoluteX),
  ("LSR", AddressMode::AbsoluteX),
  ("SRE", AddressMode::AbsoluteX),
];